[package]
name = "kongg_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
kongg_shared = { path = "../kongg_shared" }
tokio = { version = "1.44.0", features = ["rt", "macros"] }
surrealdb = { version = "2.3.1" }
