[package]
name = "kongg"
version = "0.1.0"
edition = "2024"

[dependencies]
kongg_shared = { path = "../kongg_shared" }
futures = "0.3.31"
globset = "0.4.16"
notify = "8.0.0"
tokio = { version = "1.44.0", features = ["full"] }
