[package]
name = "kongg_term"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
kongg_shared = { path = "../kongg_shared" }
ratatui = "0.29.0"
surrealdb = { version = "2.3.1" }
tokio = { version = "1.44.0", features = ["rt", "macros"] }
